### PR TITLE
Add locale processor

### PR DESCRIPTION
**Pull request by tremby**
This processor adds a tag 'locale' with the app's current locale to an outgoing report.

### CODE REVIEW

**Comment by pulkitjalan** [comment]
This can no longer be merged :(

**Comment by tremby** [comment]
Yes, that was expected, since they both added the same section to the readme, but with different subsections. I've rebased this, and it should merge now.

**Comment by pulkitjalan** [comment]
Great, Thanks!

**Comment by tremby** [comment]
No problem. If you're happy with these two, a release would be great. I also commented on an earlier commit a couple of days ago; did you see that? Not a huge deal.

**Comment by pulkitjalan** [comment]
Done, yea its now fixed. That was an accident, i was suppose to move it into the data array init. Done that now. Thanks.

**Comment by tremby** [comment]
Okay, I'm going to put the doc comment about that back in, then. Expect another PR...

**Pull request merged**
